---
title: "Clean Transcribed Data - DAM26 (assignment 3)"
author: "Matilde Elene Hansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#install packages (see ../requirements.txt)
library(dplyr)
library(tidyr)
library(rvest)

```

```{r}
# input data (raw)
raw_path <- file.path("..", "data", "raw")

# paths for output (tidy files)
tidy_path <-  file.path(
  "..", "data", "tidy"
  )
# create directory if it does not exist
if (!dir.exists(tidy_path)) {
  dir.create(tidy_path)
}

# setting figure output directory
figures_dir <- file.path("..", "out", "figures")
dir.create(
  figures_dir,
  recursive = TRUE,
  showWarnings = FALSE
)
```

```{r, raw data inspection}
# data: 
raw_data <- read_csv(file.path(raw_path, "concat_1889_1913_raw.csv"))
dim(raw_data) #should be comma-separated (3997 rows, 31 columns)

#gender-split:
raw_men <- read_csv(file.path(raw_path, "risskov_men_1889_1913_raw.csv"))
raw_women <- read_csv(file.path(raw_path, "risskov_women_1889_1913_raw.csv"))

rows_raw_men <- count(raw_men)
rows_raw_women <- count(raw_women)

cat(paste0("Women's n. of observations (raw) = ", rows_raw_women , ". \nMen's n. of observations (raw) = ", rows_raw_men,"."))
```


```{r, raw data inspection}
# inspecting a random subset
set.seed(99)

draw_random <- function(data, n = 2) {
  data %>%
    distinct(Løbenr, .keep_all = TRUE) %>%
    slice_sample(n = n)
}

# including a specific Løbenr
draw_random_include <- function(data, include_id, n = 2) {
  data_unique <- data %>%
    distinct(Løbenr, .keep_all = TRUE)
  bind_rows(
    data_unique %>% filter(Løbenr == include_id),
    data_unique %>%
      filter(Løbenr != include_id) %>%
      slice_sample(n = n - 1)
  ) %>%
    slice_sample(prop = 1)  # randomize final order
}

# men's sample includes Løbenr 4673
sample_men <- draw_random_include(
  raw_men,
  include_id = 4673,
  n = 2
)

# women's sample is fully random
sample_women <- draw_random(
  raw_women,
  n = 2
)

print(sample_men)
print(sample_women)
```


```{r, Download sampled images and annotations}
# setting output folder:
comparison_dir <- file.path("..", "out", "digitized_comparison")
dir.create(
  comparison_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

# extract archival image ID:
get_image_id <- function(transcription_url) {
  page <- read_html(transcription_url)
  links <- page %>%
    html_elements("a") %>%
    html_attr("href")
  image_link <- links[
    str_detect(links, "Fejlmelding_af_billede")
  ]

  image_id <- str_match(
    image_link,
    "bid=(\\d+)"
  )[, 2]
  return(image_id)
}

# add correct image IDs:
sample_men <- sample_men %>%
  mutate(
    image_id = sapply(transcription_url, get_image_id),
    archive_image_url = paste0(
      "https://api.rigsarkivet.dk/ao/v1/images/",
      image_id
    )
  )

sample_women <- sample_women %>%
  mutate(
    image_id = sapply(transcription_url, get_image_id),
    archive_image_url = paste0(
      "https://api.rigsarkivet.dk/ao/v1/images/",
      image_id
    )
  )

# download digitized images
save_digitized_images <- function(data, group, out_dir) {
  
  for (i in seq_len(nrow(data))) {
    
    image_url <- data$archive_image_url[i]
    loebenr <- data$Løbenr[i]
    
    file_name <- paste0(
      group, "_",
      loebenr,
      ".jpg"
    )
    
    file_path <- file.path(
      out_dir,
      file_name
    )
    
    download.file(
      url = image_url,
      destfile = file_path,
      mode = "wb",
      quiet = FALSE
    )
  }
}

# save corresponding transcribed annotations
save_sample_data <- function(data, group, out_dir) {
  for (i in seq_len(nrow(data))) {
    loebenr <- data$Løbenr[i]
    file_name <- paste0(
      group, "_",
      loebenr,
      ".csv"
    )
    file_path <- file.path(
      out_dir,
      file_name
    )
    write_csv(
      data[i, ],
      file_path
    )
  }
}

# save sampled scans and annotations (wrapper)
save_comparison <- function(data, group, out_dir) {
  save_digitized_images(data, group, out_dir)
  save_sample_data(data, group, out_dir)
}

# saving sampled scans and annotations
save_comparison(sample_men, "men", comparison_dir)
save_comparison(sample_women, "women", comparison_dir)

```
```{r, standardizing}
# creating working dataframe and standardizing column names for analysis
tidy_df <- raw_data %>%
  rename(
    patient_id = Løbenr,
    name = Navn,
    sex = Køn,
    occupation = `Stand og stilling`,
    residence = Hjemsted,
    age_at_admission = `Alder ved indlæggelsen`,
    date_of_birth = Fødselsdato,
    religion = Trosbekendelse,
    marital_status = Ægtestandsforhold,
    admission_date = `Naar ankommen`,
    admitted_from = `Hvorfra ankommen`,
    diagnosis_at_admission = `Diagnose ved indlæggelsen`,
    duration_at_admission = `Varighed ved indlæggelsen`,
    journal_number = Journalnummer,
    care_payment_class = `Forplejnings og betalingsklasse`,
    episode_number = `Anfaldets nr.`,
    remarks = Anmærkninger,
    family_disposition = Familiedisposition,
    discharge_number = `Afgået nr.`,
    discharge_date = `Afgået naar`,
    condition_at_discharge = `I hvad tilstand`,
    discharged_to = Hvorhen,
    previous_number = `Ældre nr.`,
    readmitted_under_number = `Genindlagt under nr.`,
    transcriber_notes = `Indtasters bemærkninger`
  )

#saving original archival names for labeling:
variable_labels <- tibble(
  variable = names(tidy_df),
  original_label = names(raw_data)
)
```


```{r, standardizing cells}
# tidying cells for computational analysis: 

### LOWERCASING: 
#sex and sex series: standardizing to lowercase (K --> k and M --> m)
tidy_df <- tidy_df %>%
  mutate(sex_series = tolower(sex_series)
  ) %>%
  mutate(sex=tolower(sex)
  ) %>% #also marital status and family disposition and condition at discharge
  mutate(marital_status=tolower(marital_status) 
  )%>%
  mutate(family_disposition=tolower(family_disposition)
  )%>%
  mutate(condition_at_discharge=tolower(condition_at_discharge))

###  NAs AND SIMILAR: 
# Kunne ikke udfyldes (cells) ==>
tidy_df <- tidy_df %>%
  mutate(
    across(
      where(is.character),
      ~ if_else(
        .x == "Kunne ikke udfyldes",
        "could_not_transcribe",
        .x
      )
    )
  )

```

```{r}
# total number of explicit transcription failures
cat(sum(tidy_df == "could_not_transcribe", na.rm = TRUE))

# count "could_not_transcribe" by column
could_not_transcribe_counts <- tidy_df %>%
  summarise(
    across(
      everything(),
      ~ sum(.x == "could_not_transcribe", na.rm = TRUE)
    )
  ) %>%
  pivot_longer(
    everything(),
    names_to = "variable",
    values_to = "count"
  ) %>%
  filter(count >= 10) %>%
  left_join(
    variable_labels,
    by = "variable"
  ) %>%
  arrange(count)

# plot
could_not_transcribe_plot <- ggplot(
  could_not_transcribe_counts,
  aes(
    x = count,
    y = reorder(original_label, count)
  )
) +
  geom_col() +
  labs(
    x = "Count",
    y = "Archival field",
    title = 'Occurrences of "could_not_transcribe" by archival field'
  ) +
  theme_minimal()

could_not_transcribe_plot

# saving plot
ggsave(
  filename = file.path(
    figures_dir,
    "could_not_transcribe_by_field.png"
  ),
  plot = could_not_transcribe_plot,
  width = 8,
  height = 5,
  dpi = 300
)
```
```{r}
#checking for inconsistencies between birth year and admission year
inconsistent_birth_date <- tidy_df %>%
  filter(
    date_of_birth != "could_not_transcribe",
    admission_date != "could_not_transcribe"
  ) %>%
  mutate(
    birth_year = as.numeric(sub(".*-", "", date_of_birth)),
    admission_year = as.numeric(sub(".*-", "", admission_date))
  ) %>%
  filter(
    birth_year > admission_year |
    !grepl("\\d{4}$", date_of_birth)
  ) %>%
  select(
    patient_id,
    date_of_birth,
    birth_year,
    admission_date,
    admission_year
  )

print(inconsistent_birth_date)

cat(
  "Number of patients with inconsistent birth dates:",
  nrow(inconsistent_birth_date), "\n")

# Checking for inconsistencies across admission and discharge date columns
inconsistent_admission_discharge_date <- tidy_df %>%
  filter(
    admission_date != "could_not_transcribe",
    discharge_date != "could_not_transcribe"
  ) %>%
  mutate(
    admission_year = as.numeric(sub(".*-", "", admission_date)),
    discharge_year = as.numeric(sub(".*-", "", discharge_date))
  ) %>%
  filter(
    admission_year < 1889 |
    admission_year > 1914 |
    discharge_year < admission_year
  ) %>%
  select(
    patient_id,
    admission_date,
    admission_year,
    discharge_date,
    discharge_year
  )

print(inconsistent_admission_discharge_date)

cat(
  "Number of patients with inconsistent admission/discharge dates:",
  nrow(inconsistent_admission_discharge_date),
  "\n"
)
```

```{r duplicate IDs}
# Manually inspecting and validating duplicate patient IDs
# e.g. do duplicate IDs represent readmissions?

duplicate_patients <- tidy_df %>%
  group_by(patient_id) %>%
  filter(n() > 1) %>%
  arrange(patient_id, admission_date) %>%
  select(
    patient_id,
    admission_date,
    discharge_date,
    everything()
  ) %>%
  ungroup()

print(duplicate_patients)

#if in the same sex_series 
```

```{r removing invalid patient_ids}
tidy_df <- tidy_df %>%

  # Removing patients with inconsistent admission/discharge dates
  filter(
    !patient_id %in% inconsistent_admission_discharge_date$patient_id)  %>%

  # removing manually inspected patient
  filter(
    patient_id != 4673) %>%
  
  # overriding inconsistent birth dates
 mutate(
    date_of_birth = if_else(
      patient_id %in% inconsistent_birth_date$patient_id,
      NA_character_,
      date_of_birth
    )
  )

# Removing duplicates from analytical sample (if necessary)

# checking number of NA in date_of_birth as sanity check
sum(is.na(tidy_df$date_of_birth)) # correctly prints 9 as expected.
```

```{r, birth date trend}
# birth dates column
n_birth_dates <- tidy_df %>%
  filter(date_of_birth != "could_not_transcribe") %>%
  summarise(n = n()) %>%
  pull(n)

cat(paste0("Number of eligible annotations for birth dates: ", n_birth_dates,"\n"))

#admission dates column
n_admission_dates <- tidy_df %>%
  filter(admission_date != "could_not_transcribe") %>%
  summarise(n = n()) %>%
  pull(n)

cat(paste0("Number of eligible annotations for admission dates: ", n_admission_dates,"\n"))

#discharge dates column
n_discharge_dates <- tidy_df %>%
  filter(discharge_date != "could_not_transcribe") %>%
  summarise(n = n()) %>%
  pull(n)

cat(paste0("Number of eligible annotations for discharge dates: ", n_discharge_dates,"\n"))

# 
birth_date_trend <- tidy_df %>%
  mutate(
    admission_year = as.numeric(sub(".*-", "", admission_date)),
    birth_date_status = case_when(
      is.na(date_of_birth) ~ "invalid_removed",
      date_of_birth == "could_not_transcribe" ~ "could_not_transcribe",
      TRUE ~ "transcribed"
    )
  ) %>%
  count(admission_year, birth_date_status) %>%
  group_by(admission_year) %>%
  mutate(
    proportion = n / sum(n)
  ) %>%
  ungroup()

  #plotting trend
birth_date_trend_plot <- ggplot(
  birth_date_trend,
  aes(
    x = admission_year,
    y = proportion,
    fill = birth_date_status
  )
) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Birth-date annotations by year of admission",
    x = "Year of admission",
    y = "Proportion of records",
    fill = "Birth date status"
  ) +
  theme_minimal()

birth_date_trend_plot
```

```{r, duplicates}

```

