---
title: "Clean Transcribed Data - DAM26 (assignment 3)"
author: "Matilde Elene Hansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#install packages (see ../requirements.txt)
library(tidyverse)
library(dplyr)
library(tidyr)
library(rvest)
```

```{r}
# setting paths

# input data (raw)
raw_path <- file.path("..", "data", "raw_data")

# paths for output (tidy files)
tidy_path <-  file.path(
  "..", "data", "tidy_data"
)
# create directory if it does not exist
if (!dir.exists(tidy_path)) {
  dir.create(tidy_path)
}

out_dir <- file.path("..", "out")
dir.create(
  out_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

# setting figure output directory
figures_dir <- file.path("..", "out", "figures")
dir.create(
  figures_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

# setting output folder:
comparison_dir <- file.path("..", "out", "digitized_comparison")
dir.create(
  comparison_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

#out path for analytical sample 
analysis_df_dir <- file.path("..", "data","analysis_data")
dir.create(
  analysis_df_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

```


```{r, raw data inspection}
# data: 
raw_data <- read_csv(file.path(raw_path, "concat_1889_1913_raw.csv"))
glimpse(raw_data) #should be comma-separated (3997 rows, 31 columns)

#gender-split:
raw_men <- read_csv(file.path(raw_path, "risskov_men_1889_1913_raw.csv"))
raw_women <- read_csv(file.path(raw_path, "risskov_women_1889_1913_raw.csv"))

rows_raw_men <- count(raw_men)
rows_raw_women <- count(raw_women)

cat(paste0("Women's n. of observations (raw) = ", rows_raw_women , ". \nMen's n. of observations (raw) = ", rows_raw_men,"."))
```


```{r, raw data inspection}
# inspecting a random subset
set.seed(99)

draw_random <- function(data, n = 2) {
  data %>%
    distinct(Løbenr, .keep_all = TRUE) %>%
    slice_sample(n = n)
}

# including a specific Løbenr
draw_random_include <- function(data, include_id, n = 2) {
  data_unique <- data %>%
    distinct(Løbenr, .keep_all = TRUE)
  bind_rows(
    data_unique %>% filter(Løbenr == include_id),
    data_unique %>%
      filter(Løbenr != include_id) %>%
      slice_sample(n = n - 1)
  ) %>%
    slice_sample(prop = 1)  # randomize final order
}

# men's sample includes Løbenr 4673
sample_men <- draw_random_include(
  raw_men,
  include_id = 4673,
  n = 2
)

# women's sample is fully random
sample_women <- draw_random(
  raw_women,
  n = 2
)

print(sample_men)
print(sample_women)
```


```{r, Download sampled images and annotations}
# setting output folder:
comparison_dir <- file.path("..", "out", "digitized_comparison")
dir.create(
  comparison_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

# extract archival image ID:
get_image_id <- function(transcription_url) {
  page <- read_html(transcription_url)
  links <- page %>%
    html_elements("a") %>%
    html_attr("href")
  image_link <- links[
    str_detect(links, "Fejlmelding_af_billede")
  ]

  image_id <- str_match(
    image_link,
    "bid=(\\d+)"
  )[, 2]
  return(image_id)
}

# add correct image IDs:
sample_men <- sample_men %>%
  mutate(
    image_id = sapply(transcription_url, get_image_id),
    archive_image_url = paste0(
      "https://api.rigsarkivet.dk/ao/v1/images/",
      image_id
    )
  )

sample_women <- sample_women %>%
  mutate(
    image_id = sapply(transcription_url, get_image_id),
    archive_image_url = paste0(
      "https://api.rigsarkivet.dk/ao/v1/images/",
      image_id
    )
  )

# download digitized images
save_digitized_images <- function(data, group, out_dir) {
  
  for (i in seq_len(nrow(data))) {
    
    image_url <- data$archive_image_url[i]
    loebenr <- data$Løbenr[i]
    
    file_name <- paste0(
      group, "_",
      loebenr,
      ".jpg"
    )
    
    file_path <- file.path(
      out_dir,
      file_name
    )
    
    download.file(
      url = image_url,
      destfile = file_path,
      mode = "wb",
      quiet = FALSE
    )
  }
}

# save corresponding transcribed annotations
save_sample_data <- function(data, group, out_dir) {
  for (i in seq_len(nrow(data))) {
    loebenr <- data$Løbenr[i]
    file_name <- paste0(
      group, "_",
      loebenr,
      ".csv"
    )
    file_path <- file.path(
      out_dir,
      file_name
    )
    write_csv(
      data[i, ],
      file_path
    )
  }
}

# save sampled scans and annotations (wrapper)
save_comparison <- function(data, group, out_dir) {
  save_digitized_images(data, group, out_dir)
  save_sample_data(data, group, out_dir)
}

# saving sampled scans and annotations
save_comparison(sample_men, "men", comparison_dir)
save_comparison(sample_women, "women", comparison_dir)

```
```{r defining function for cleaning}
check_noncompliant <- function(data, variable, expected_values) {
  data %>%
    filter(
      !is.na({{ variable }}),
      !{{ variable }} %in% expected_values
    ) %>%
    count({{ variable }}, sort = TRUE)
}
```

```{r, standardizing}
# creating working dataframe and standardizing column names for analysis
tidy_df <- raw_data %>%
  rename(
    patient_id = Løbenr,
    name = Navn,
    sex = Køn,
    occupation = `Stand og stilling`,
    residence = Hjemsted,
    age_at_admission = `Alder ved indlæggelsen`,
    date_of_birth = Fødselsdato,
    religion = Trosbekendelse,
    marital_status = Ægtestandsforhold,
    admission_date = `Naar ankommen`,
    admitted_from = `Hvorfra ankommen`,
    diagnosis_at_admission = `Diagnose ved indlæggelsen`,
    duration_at_admission = `Varighed ved indlæggelsen`,
    journal_number = Journalnummer,
    care_payment_class = `Forplejnings og betalingsklasse`,
    episode_number = `Anfaldets nr.`,
    remarks = Anmærkninger,
    family_disposition = Familiedisposition,
    discharge_number = `Afgået nr.`,
    discharge_date = `Afgået naar`,
    condition_at_discharge = `I hvad tilstand`,
    discharged_to = Hvorhen,
    previous_number = `Ældre nr.`,
    readmitted_under_number = `Genindlagt under nr.`,
    transcriber_notes = `Indtasters bemærkninger`
  )

#saving original archival names for labeling:
variable_labels <- tibble(
  variable = names(tidy_df),
  original_label = names(raw_data)
)
```

```{r}
###  TRANSCRIPTION STATUS
# Standardize all capitalization variants of explicit transcription failures while preserving them as distinct from missing (NA) values
tidy_df <- tidy_df %>%
  mutate(
    across(
      where(is.character),
      ~ if_else(
        str_to_lower(.x) == "kunne ikke udfyldes",
        "could_not_transcribe",
        .x
      )
    )
  )
```


```{r, standardizing_cells_cat}
### STANDARDIZING CATEGORICAL VARIABLES
# Lowercase, remove punctuation, and standardize whitespace, while preserving explicit transcription-status values

tidy_df <- tidy_df %>%
  mutate(
    across(
      c(
        sex_series,
        sex,
        marital_status,
        family_disposition,
        condition_at_discharge
      ),
      ~ if_else(
        .x == "could_not_transcribe",
        .x,
        .x %>%
          tolower() %>%
          str_remove_all("[[:punct:]]") %>%
          str_squish()
      )
    )
  )

### INSPECTING CATEGORICAL VALUES
categorical_counts_pre <- tidy_df %>%
  select(
    sex_series,
    sex,
    marital_status,
    family_disposition,
    condition_at_discharge,
    diagnosis_at_admission
  ) %>%
  pivot_longer(
    cols = everything(),
    names_to = "variable",
    values_to = "value"
  ) %>%
  count(variable, value, sort = TRUE)

#number of unique values per variable (pre-cleaning)
unique_values_pre_cleaning <- categorical_counts_pre %>%
  group_by(variable) %>%
  summarise(n_unique = n())

# inspecting selected value distributions
tidy_df %>%
  select(patient_id, marital_status)  %>%
  count(marital_status, sort = TRUE)
tidy_df %>%
  count(family_disposition, sort = TRUE)
```


```{r defining_recodes}

#setting expected values for analysis: 
expected_sex <- c("k", "m") # 2 are expected
expected_m_status <- c("enke", "gift", "ugift", "separeret","fraskilt") 
expected_family_disposition <- c("ja","nej")

# condition_at_discharge and diagnosis_at_admission have too many unique values for manual standardization at this stage and are kept as-is.

#manual recoding dictionaries
sex_recode <- c(
  "kvinde" = "k",
  "mand"   = "m",
  "mnd"    = "m"
)

m_status_recode <- c(
  "ug" = "ugift",
  "g" = "gift",
  "u" ="ugift",
  "ugicft"="ugift",	
  "ugioft"="ugift",
  "g enke" = "enke",
  "e" = "enke",
  "gifi" = "gift",
  "enkem" = "enke",
  "enkemd" = "enke",
  "eknem" = "enke",
  "enkemand" = "enke",
  "sep" = "separeret",
  "separ" = "separeret",
  "s" = "separeret",
  "separe" = "separeret",
  "seper" = "separeret",
  "sepereret"	= "separeret",			
  "frask" = "fraskilt",
  "frs" = "fraskilt",
  "fraskilt forladt kone" = "fraskilt",
  "frsk" = "fraskilt",
  "g separeret" = "separeret"
)

family_disposition_recode <- c(
  "jq" = "ja",
  "js" = "ja",
  "nje" = "nej"
)

```

```{r applying_cat_recodes}
# Applying manual recodes
tidy_df <- tidy_df %>%
  mutate(
    sex = recode(
      sex,
      !!!sex_recode,
      .default = sex
    ),

    marital_status = recode(
      marital_status,
      !!!m_status_recode,
      .default = marital_status
    ),
    marital_status = na_if(marital_status, ""),
    # Empty cells are missing values, not transcription failures

    family_disposition = recode(
      family_disposition,
      !!!family_disposition_recode,
      .default = family_disposition
    ),
    family_disposition = na_if(family_disposition, "")
  ) # Empty cells are missing values, not transcription failures
```


```{r dbl_checking_cat_var}
# Double checking non-compliant values
check_noncompliant(
  tidy_df,
  sex,
  expected_sex
)

check_noncompliant(
  tidy_df,
  marital_status,
  expected_m_status
)

check_noncompliant(
  tidy_df,
  family_disposition,
  expected_family_disposition
)

### INSPECTING CATEGORICAL VALUES — POST-CLEANING
categorical_counts_post <- tidy_df %>%
  select(
    sex,
    marital_status,
    family_disposition
  ) %>%
  pivot_longer(
    cols = everything(),
    names_to = "variable",
    values_to = "value"
  ) %>%
  count(variable, value, sort = TRUE)

# Number of unique values after manual recoding
unique_values_post_cleaning <- categorical_counts_post %>%
  group_by(variable) %>%
  summarise(n_unique = n_distinct(value))
```

```{r, standardizing categorical values 2}
# total number of explicit transcription failures
cat(sum(tidy_df == "could_not_transcribe", na.rm = TRUE))

# count "could_not_transcribe" by column
could_not_transcribe_counts <- tidy_df %>%
  summarise(
    across(
      everything(),
      ~ sum(.x == "could_not_transcribe", na.rm = TRUE)
    )
  ) %>%
  pivot_longer(
    everything(),
    names_to = "variable",
    values_to = "count"
  ) %>%
  filter(count >= 10) %>%
  left_join(
    variable_labels,
    by = "variable"
  ) %>%
  arrange(count)

# plot
could_not_transcribe_plot <- ggplot(
  could_not_transcribe_counts,
  aes(
    x = count,
    y = reorder(original_label, count)
  )
) +
  geom_col(fill = "steelblue") +
  labs(
    x = "Count",
    y = "Archival field",
    title = 'Occurences of Non-Transcribable Fields (Tidy data)'
  ) +
  theme_minimal()

could_not_transcribe_plot

# saving plot
ggsave(
  filename = file.path(
    figures_dir,
    "could_not_transcribe_by_field.png"
  ),
  plot = could_not_transcribe_plot,
  width = 8,
  height = 5,
  dpi = 300
)
```

```{r duplicate_patient_check}
### CHECKING DUPLICATE PATIENT RECORDS
# e.g. do duplicate patient_IDs represent readmissions?

# Remove exact duplicates where patient ID, sex series, admission_date, and name are identical
tidy_df <- tidy_df %>%
  group_by(sex_series, patient_id, name) %>%
  filter(n() == 1) %>%
  ungroup()

# Inspect remaining duplicate IDs occurring within the same sex series (i.e. same ID but different names)
duplicate_patients_to_inspect <- tidy_df %>%
  group_by(sex_series, patient_id) %>%
  filter(n() > 1) %>%
  arrange(sex_series, patient_id, admission_date) %>%
  select(
    sex_series,
    patient_id,
    name,
    admission_date,
    everything()
  ) %>%
  ungroup()

# saving to "out" for manual inspection
write_csv(
  duplicate_patients_to_inspect,
  file.path(out_dir, "duplicate_patients_to_inspect.csv")
)
```

```{r admission_discharge_date_check}
# Checking for inconsistent admission and discharge dates
inconsistent_admission_discharge_date <- tidy_df %>%
  filter(
    !is.na(admission_date),
    admission_date != "could_not_transcribe"
  ) %>%
  mutate(
    admission_year = as.numeric(
      str_extract(admission_date, "\\d{4}$")
    ),
    discharge_year = as.numeric(
      str_extract(discharge_date, "\\d{4}$")
    )
  ) %>%
  filter(
    # Admission must fall within study period
    is.na(admission_year) |
      admission_year < 1889 |
      admission_year > 1914 |

    # Discharge cannot precede admission
    (!is.na(discharge_year) &
       discharge_year < admission_year)
  ) %>%
  select(
    sex_series,
    patient_id,
    admission_date,
    admission_year,
    discharge_date,
    discharge_year
  )

print(inconsistent_admission_discharge_date)

cat(
  "Number of patients with inconsistent admission/discharge dates:",
  nrow(inconsistent_admission_discharge_date),
  "\n"
)
```

```{r birth_date_makes_no_sense}
# Checking for inconsistencies between birth year and admission year
inconsistent_birth_date <- tidy_df %>%
  filter(
    !is.na(date_of_birth),
    !is.na(admission_date),
    date_of_birth != "could_not_transcribe",
    admission_date != "could_not_transcribe"
  ) %>%
  mutate(
    birth_year = as.numeric(
      str_extract(date_of_birth, "\\d{4}$")
    ),
    admission_year = as.numeric(
      str_extract(admission_date, "\\d{4}$")
    )
  ) %>%
  filter(
    birth_year > admission_year |
      is.na(birth_year)
  ) %>%
  select(
    sex_series,
    patient_id,
    date_of_birth,
    birth_year,
    admission_date,
    admission_year
  )

print(inconsistent_birth_date)
cat(
  "Number of patients with inconsistent birth dates:",
  nrow(inconsistent_birth_date),
  "\n"
)
```

```{r birth_date_trend}

# Keys for records whose birth dates were identified as invalid
inconsistent_birth_keys <- inconsistent_birth_date %>%
  transmute(
    record_key = paste(sex_series, patient_id, sep = "_")
  ) %>%
  pull(record_key)

birth_date_trend <- tidy_df %>%
  mutate(
    record_key = paste(sex_series, patient_id, sep = "_"),

    admission_year = as.numeric(
      str_extract(admission_date, "\\d{4}$")
    ),
    birth_date_status = case_when(
      record_key %in% inconsistent_birth_keys ~ "invalid_removed",
      !is.na(date_of_birth) &
        date_of_birth != "could_not_transcribe" ~ "transcribed",
      TRUE ~ "could_not_transcribe"
    )
  ) %>%
  filter(!is.na(admission_year)) %>%
  count(admission_year, birth_date_status) %>%
  group_by(admission_year) %>%
  mutate(
    proportion = n / sum(n)
  ) %>%
  ungroup()


# Plotting trend
birth_date_trend_plot <- ggplot(
  birth_date_trend,
  aes(
    x = admission_year,
    y = proportion,
    fill = birth_date_status
  )
) +
  geom_col() +
  scale_x_continuous(
    breaks = c(1889, 1894, 1899, 1904, 1909, 1913),
    limits = c(1889, 1913)
    ) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "Birth-date annotations by year of admission",
    x = "Year of admission",
    y = "Proportion of records",
    fill = "Birth date status"
  ) +
  theme_minimal()

birth_date_trend_plot
# Saving plot
ggsave(
  filename = file.path(
    figures_dir,
    "birth_date_trend.png"
  ),
  plot = birth_date_trend_plot,
  width = 8,
  height = 5,
  dpi = 300
)

```

```{r new_df_analysis}
inconsistent_birth_keys <- inconsistent_birth_date %>%
  transmute(
    record_key = paste(sex_series, patient_id, sep = "_")
  ) %>%
  pull(record_key)

inconsistent_date_keys <- inconsistent_admission_discharge_date %>%
  transmute(
    record_key = paste(sex_series, patient_id, sep = "_")
  ) %>%
  pull(record_key)

```

```{r creating analysis_df}
# NEW DF FOR ANALYTICAL SAMPLE: 
analysis_df <- tidy_df %>%
  mutate(
    record_key = paste(sex_series, patient_id, sep = "_"),

    # Invalid birth-date annotation affects only that field
    date_of_birth = if_else(
      record_key %in% inconsistent_birth_keys,
      NA_character_,
      date_of_birth
    )
  ) %>%

  # Invalid admission/discharge dates affect record eligibility
  filter(
    !record_key %in% inconsistent_date_keys,
    patient_id != "4673"
  )


#Creating a unique ID to make sure no patient_IDs are duplicated
analysis_df <- analysis_df %>%
  mutate(
    patient_key = paste(sex_series, patient_id, sep = "_")
  )

```

```{r load_data}
# for analysis, checking dataframe structure and dimensions
str(analysis_df) #should be comma-separated (3997 rows, 31 columns)

#this time, transcription notes are omitted, and treated as NA:
analysis_df <- analysis_df %>%
  mutate(
    across(
      where(is.character),
      ~ na_if(.x, "could_not_transcribe")
    )
  )

# changing data types:
analysis_df <- analysis_df %>%
  mutate(
    # Standardizing dates from d-m-y to y-m-d
    admission_date = as.Date(admission_date, format = "%d-%m-%Y"),
    discharge_date = as.Date(discharge_date, format = "%d-%m-%Y"),
    date_of_birth = as.Date(date_of_birth, format = "%d-%m-%Y"),

    # Extracting years
    birth_year = lubridate::year(date_of_birth),
    admission_year = lubridate::year(admission_date),
    discharge_year = lubridate::year(discharge_date),

    # Factorizing defined categorical variables
    sex_series = factor(sex_series),
    sex = factor(sex),
    marital_status = factor(marital_status),

    # Numeric / sequential variables
    series_page = as.integer(series_page),
    crowd_id = as.integer(crowd_id),
    
    #cat:
    patient_key = as.character(patient_key)
  )

# Saving analytical sample dataframe
write_csv(
  analysis_df,
  file.path(analysis_df_dir, "analysis_df.csv")
)
```

