---
title: 'Monarchs Portfolio Assignment: Element 1'
author: "Matilde Elene"
date: "July 31st"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = "..")
```

```{r, echo=FALSE}
#loading packages 
library(pacman)
pacman::p_load(ggplot2, tidyverse, tibble)
```

**Element 1:** Creating a "tidy" csv file of a monarchy with 5 variables including the monarch's name (monarch_name), birth date (dateBirth), start of reign date (startReign), and end of reign date (endReign).

### Creating a Tibble

```{r}
#creating a tibble
tib <- tibble(
monarch_name = c("Gorm the Old","Harald I", "Sweyn I", "Harald II", "Canute II", "Hardecanute", "Magnus I Olafsson", "Sweyn II Estridsen", "Harald III", "Canute IV", "Olaf I", "Erik I", "Niels","Erik II", "Erik III", "Sweyn III", "Valdemar I", "Canute VI", "Valdemar II", "Erik IV", "Abel", "Christoper I", "Erik V", "Erik VI", "Christoper II", "Valdermar IV Atterdag", "Olaf II", "Margaret I", "Erik VII of Pomerania", "Christopher III of Bavaria", "Christian I", "John (Hans)", "Christian II", "Frederick I", "Christian III", "Frederick II", "Christian IV", "Frederick III", "Christian V", "Frederick IV", "Christian VI", "Frederick V", "Christian VII", "Frederick VI", "Christian VIII", "Frederick VII", "Christian IX", "Frederick VIII", "Christian X", "Frederick IX", "Margrethe II", "Frederick X"
      ), # Sweyn III reigned concurrently with Canute V and later Valdemar I; the overlapping reigns are not clearly reflected in the source used for this dataset.
                    # interregnum from 1332-40
monarch_house =c("House of Gorm","House of Gorm","House of Gorm","House of Gorm","House of Gorm","House of Gorm","House of Fairhair","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Estridsen","House of Bjälbo","House of Estridsen","House of Griffin","House of Wittelsbach, Palatinate-Neumarkt branch","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","House of Oldenburg","Schleswig-Holstein-Sonderburg-Glücksburg branch","Schleswig-Holstein-Sonderburg-Glücksburg branch","Schleswig-Holstein-Sonderburg-Glücksburg branch","Schleswig-Holstein-Sonderburg-Glücksburg branch","Schleswig-Holstein-Sonderburg-Glücksburg branch","Schleswig-Holstein-Sonderburg-Glücksburg branch"),
date_birth = c(NA,"932","963",NA,"985","1020","1024","1019","1040","1042","1050","1060","1065","1090","1120","1125","1131","1163","1170","1216","1218","1219","1249","1274","1276","1320","1370","1353","1381","1416","1426","1455","1481","1471","1503","1534","1577","1609","1646","1671","1699","1723","1749","1768","1786","1808","1818","1843","1870", "1899","1940","1968"),
date_death = c("958","985","1014","1018","1035","1042","1047","1076","1080","1086","1095","1103","1134","1137","1146", "1157","1182","1202","1241","1250","1252","1259","1286","1319","1332","1375","1387","1412","1459","1448","1481","1513","1559","1533","1559","1588","1648","1670","1699","1730","1746","1766","1808","1839","1848","1863","1906","1912","1947","1972", NA, NA),
start_reign = c(NA,"958","987","1014","1019","1028","1042", "1047", "1074", "1080", "1086", "1095", "1104", "1134", "1137", "1146", "1157", "1182", "1202", "1241", "1250", "1252", "1259", "1286", "1319", "1340", "1376", "1387", "1412", "1440", "1448", "1481", "1513", "1523", "1534", "1559", "1588", "1648", "1670", "1699", "1730", "1746", "1766", "1808", "1839", "1848", "1863", "1906", "1912", "1947", "1972", "2024"),
end_reign = c("958","985","1014","1018","1035","1042","1047","1074", "1080","1086","1095","1103","1134","1137", "1146", "1157","1182","1202","1241", "1250", "1252", "1259", "1286", "1319", "1332","1375","1387","1412","1439","1448","1481","1513","1523","1533", "1559", "1588", "1648", "1670", "1699", "1730", "1746", "1766", "1808", "1839", "1848", "1863","1906","1912","1947","1972","2024",NA))

#inspecting the first part of the data
print(tib)
```
```{r}
# Making sure there are no duplicates, aka (an error ID-10T)
cat("Number of duplicate names:", anyDuplicated(tib$monarch_name))
```

```{r}
# saving original dataset:
write.csv(tib,file = "../data/danish_monarchy.csv",row.names=FALSE, na = "") 
```

```{r}
#converting the tibble to a dataframe and creating a reproducible monarch ID
df <- as.data.frame(tib) %>%
  mutate(monarch_id = monarch_name %>%
           str_to_lower() %>%
           str_replace_all("\\s+", "_"),
         .after = monarch_name)

# creating a reproducible house ID by removing commas and replacing spaces with underscores
df <- df %>%
  mutate(house_id = monarch_house %>%
           str_to_lower() %>%
           str_replace_all(",", "") %>% 
           str_replace_all("\\s+", "_"),
         .after = monarch_house)

head(df)
```

```{r}
# saving tidy dataset: 
write.csv(df,file = "../data/monarchy_data.csv",row.names=FALSE, na = "") 
```

